# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: skttr87.getsu
PackageVersion: 1.1.0
InstallerType: inno
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/skttr87/getsu/releases/download/v1.1.0/Getsu-v1.1.0-Setup.exe
    InstallerSha256: 327DE5CCE1109E4132C0A311E72FCF8013C658435116714D0BF2F13BFB2C08F0
    ProductCode: '{8B4F923D-567A-4831-9F3B-2A58C7E1B455}_is1'
ManifestType: installer
ManifestVersion: 1.6.0
